/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardUploadRouteImport } from './routes/dashboard.upload'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardPricesRouteImport } from './routes/dashboard.prices'
import { Route as DashboardMedicinesRouteImport } from './routes/dashboard.medicines'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as DashboardAssistantRouteImport } from './routes/dashboard.assistant'
import { Route as DashboardPrescriptionIdRouteImport } from './routes/dashboard.prescription.$id'
import { Route as DashboardMedicineIdRouteImport } from './routes/dashboard.medicine.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUploadRoute = DashboardUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPricesRoute = DashboardPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMedicinesRoute = DashboardMedicinesRouteImport.update({
  id: '/medicines',
  path: '/medicines',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssistantRoute = DashboardAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPrescriptionIdRoute = DashboardPrescriptionIdRouteImport.update({
  id: '/prescription/$id',
  path: '/prescription/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMedicineIdRoute = DashboardMedicineIdRouteImport.update({
  id: '/medicine/$id',
  path: '/medicine/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/assistant': typeof DashboardAssistantRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/medicines': typeof DashboardMedicinesRoute
  '/dashboard/prices': typeof DashboardPricesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/medicine/$id': typeof DashboardMedicineIdRoute
  '/dashboard/prescription/$id': typeof DashboardPrescriptionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/assistant': typeof DashboardAssistantRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/medicines': typeof DashboardMedicinesRoute
  '/dashboard/prices': typeof DashboardPricesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/medicine/$id': typeof DashboardMedicineIdRoute
  '/dashboard/prescription/$id': typeof DashboardPrescriptionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/assistant': typeof DashboardAssistantRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/medicines': typeof DashboardMedicinesRoute
  '/dashboard/prices': typeof DashboardPricesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/medicine/$id': typeof DashboardMedicineIdRoute
  '/dashboard/prescription/$id': typeof DashboardPrescriptionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard/assistant'
    | '/dashboard/history'
    | '/dashboard/medicines'
    | '/dashboard/prices'
    | '/dashboard/settings'
    | '/dashboard/upload'
    | '/dashboard/'
    | '/dashboard/medicine/$id'
    | '/dashboard/prescription/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard/assistant'
    | '/dashboard/history'
    | '/dashboard/medicines'
    | '/dashboard/prices'
    | '/dashboard/settings'
    | '/dashboard/upload'
    | '/dashboard'
    | '/dashboard/medicine/$id'
    | '/dashboard/prescription/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard/assistant'
    | '/dashboard/history'
    | '/dashboard/medicines'
    | '/dashboard/prices'
    | '/dashboard/settings'
    | '/dashboard/upload'
    | '/dashboard/'
    | '/dashboard/medicine/$id'
    | '/dashboard/prescription/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/upload': {
      id: '/dashboard/upload'
      path: '/upload'
      fullPath: '/dashboard/upload'
      preLoaderRoute: typeof DashboardUploadRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/prices': {
      id: '/dashboard/prices'
      path: '/prices'
      fullPath: '/dashboard/prices'
      preLoaderRoute: typeof DashboardPricesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/medicines': {
      id: '/dashboard/medicines'
      path: '/medicines'
      fullPath: '/dashboard/medicines'
      preLoaderRoute: typeof DashboardMedicinesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assistant': {
      id: '/dashboard/assistant'
      path: '/assistant'
      fullPath: '/dashboard/assistant'
      preLoaderRoute: typeof DashboardAssistantRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/prescription/$id': {
      id: '/dashboard/prescription/$id'
      path: '/prescription/$id'
      fullPath: '/dashboard/prescription/$id'
      preLoaderRoute: typeof DashboardPrescriptionIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/medicine/$id': {
      id: '/dashboard/medicine/$id'
      path: '/medicine/$id'
      fullPath: '/dashboard/medicine/$id'
      preLoaderRoute: typeof DashboardMedicineIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAssistantRoute: typeof DashboardAssistantRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardMedicinesRoute: typeof DashboardMedicinesRoute
  DashboardPricesRoute: typeof DashboardPricesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUploadRoute: typeof DashboardUploadRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardMedicineIdRoute: typeof DashboardMedicineIdRoute
  DashboardPrescriptionIdRoute: typeof DashboardPrescriptionIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAssistantRoute: DashboardAssistantRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardMedicinesRoute: DashboardMedicinesRoute,
  DashboardPricesRoute: DashboardPricesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUploadRoute: DashboardUploadRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardMedicineIdRoute: DashboardMedicineIdRoute,
  DashboardPrescriptionIdRoute: DashboardPrescriptionIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
